sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8

install: mvn install -DskipTests -Dgpg.skip

after_success:
  - mvn clean verify jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN